#!/bin/bash

echo "BBB'deki varsayılan apply-conf.sh'yi özelleştirilmiş sürümünüzle değiştirme"
cp apply-config.sh /etc/bigbluebutton/bbb-conf/apply-config.sh
cp default.pdf /var/www/bigbluebutton-default/
cp favicon.ico /var/www/bigbluebutton-default/
cp default.pptx /var/www/bigbluebutton-default/
cp index.html /var/www/bigbluebutton-default/
cp tr_TR.json /usr/share/meteor/bundle/programs/server/assets/app/locales/
cp logo.png /var/bigbluebutton/playback/presentation/2.0/
cp conf-enter_conf_pin.wav /etc/bigbluebutton/bbb-conf/
cp conf-entry_sound.wav /etc/bigbluebutton/bbb-conf/
cp conf-exit_sound.wav /etc/bigbluebutton/bbb-conf/
cp conf-goodbye.wav /etc/bigbluebutton/bbb-conf/
cp conf-has_joined.wav /etc/bigbluebutton/bbb-conf/
cp conf-has_left.wav /etc/bigbluebutton/bbb-conf/
cp conf-is-locked.wav /etc/bigbluebutton/bbb-conf/
cp conf-is-unlocked.wav /etc/bigbluebutton/bbb-conf/
cp conf-kicked.wav /etc/bigbluebutton/bbb-conf/
cp conf-listener_in_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-listeners_in_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-locked.wav /etc/bigbluebutton/bbb-conf/
cp conf-members_in_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-muted.wav /etc/bigbluebutton/bbb-conf/
cp conf-number_of_listeners.wav /etc/bigbluebutton/bbb-conf/
cp conf-one_other_member_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-one_other_person_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-other_persons_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-pin.wav /etc/bigbluebutton/bbb-conf/
cp conf-qna_mode.wav /etc/bigbluebutton/bbb-conf/
cp conf-unmuted.wav /etc/bigbluebutton/bbb-conf/
cp conf-welcome.wav /etc/bigbluebutton/bbb-conf/
cp conf-you_are_already_muted.wav /etc/bigbluebutton/bbb-conf/
cp conf-you_are_now_bidirectionally_muted.wav /etc/bigbluebutton/bbb-conf/
cp conf-alone.wav /etc/bigbluebutton/bbb-conf/
cp conf-bad-pin.wav /etc/bigbluebutton/bbb-conf/
cp conf-conference_is_full.wav /etc/bigbluebutton/bbb-conf/
cp conf-conference_is_in_qna_mode.wav /etc/bigbluebutton/bbb-conf/
cp conf-conference_will_start_shortly.wav /etc/bigbluebutton/bbb-conf/
cp conf-enter_conf_number.wav /etc/bigbluebutton/bbb-conf/
cp conf-enter_conf_pin.wav /etc/bigbluebutton/bbb-conf/
cp conf-entry_sound.wav /etc/bigbluebutton/bbb-conf/
cp conf-exit_sound.wav /etc/bigbluebutton/bbb-conf/
cp conf-goodbye.wav /etc/bigbluebutton/bbb-conf/
cp conf-has_joined.wav /etc/bigbluebutton/bbb-conf/
cp conf-has_left.wav /etc/bigbluebutton/bbb-conf/
cp conf-is-locked.wav /etc/bigbluebutton/bbb-conf/
cp conf-is-unlocked.wav /etc/bigbluebutton/bbb-conf/
cp conf-kicked.wav /etc/bigbluebutton/bbb-conf/
cp conf-listener_in_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-listeners_in_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-locked.wav /etc/bigbluebutton/bbb-conf/
cp conf-members_in_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-muted.wav /etc/bigbluebutton/bbb-conf/
cp conf-number_of_listeners.wav /etc/bigbluebutton/bbb-conf/
cp conf-one_other_member_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-one_other_person_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-other_persons_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-pin.wav /etc/bigbluebutton/bbb-conf/
cp conf-qna_mode.wav /etc/bigbluebutton/bbb-conf/
cp conf-unmuted.wav /etc/bigbluebutton/bbb-conf/
cp conf-welcome.wav /etc/bigbluebutton/bbb-conf/
cp conf-you_are_already_muted.wav /etc/bigbluebutton/bbb-conf/
cp conf-you_are_now_bidirectionally_muted.wav /etc/bigbluebutton/bbb-conf/
cp conf-alone.wav /etc/bigbluebutton/bbb-conf/
cp conf-bad-pin.wav /etc/bigbluebutton/bbb-conf/
cp conf-conference_is_full.wav /etc/bigbluebutton/bbb-conf/
cp conf-conference_is_in_qna_mode.wav /etc/bigbluebutton/bbb-conf/
cp conf-conference_will_start_shortly.wav /etc/bigbluebutton/bbb-conf/
cp conf-enter_conf_number.wav /etc/bigbluebutton/bbb-conf/
cp conf-enter_conf_pin.wav /etc/bigbluebutton/bbb-conf/
cp conf-entry_sound.wav /etc/bigbluebutton/bbb-conf/
cp conf-exit_sound.wav /etc/bigbluebutton/bbb-conf/
cp conf-goodbye.wav /etc/bigbluebutton/bbb-conf/
cp conf-has_joined.wav /etc/bigbluebutton/bbb-conf/
cp conf-has_left.wav /etc/bigbluebutton/bbb-conf/
cp conf-is-locked.wav /etc/bigbluebutton/bbb-conf/
cp conf-is-unlocked.wav /etc/bigbluebutton/bbb-conf/
cp conf-kicked.wav /etc/bigbluebutton/bbb-conf/
cp conf-listener_in_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-listeners_in_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-locked.wav /etc/bigbluebutton/bbb-conf/
cp conf-members_in_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-muted.wav /etc/bigbluebutton/bbb-conf/
cp conf-number_of_listeners.wav /etc/bigbluebutton/bbb-conf/
cp conf-one_other_member_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-one_other_person_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-other_persons_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-pin.wav /etc/bigbluebutton/bbb-conf/
cp conf-qna_mode.wav /etc/bigbluebutton/bbb-conf/
cp conf-unmuted.wav /etc/bigbluebutton/bbb-conf/
cp conf-welcome.wav /etc/bigbluebutton/bbb-conf/
cp conf-you_are_already_muted.wav /etc/bigbluebutton/bbb-conf/
cp conf-you_are_now_bidirectionally_muted.wav /etc/bigbluebutton/bbb-conf/
cp conf-alone.wav /etc/bigbluebutton/bbb-conf/
cp conf-bad-pin.wav /etc/bigbluebutton/bbb-conf/
cp conf-conference_is_full.wav /etc/bigbluebutton/bbb-conf/
cp conf-conference_is_in_qna_mode.wav /etc/bigbluebutton/bbb-conf/
cp conf-conference_will_start_shortly.wav /etc/bigbluebutton/bbb-conf/
cp conf-enter_conf_number.wav /etc/bigbluebutton/bbb-conf/
cp conf-enter_conf_pin.wav /etc/bigbluebutton/bbb-conf/
cp conf-entry_sound.wav /etc/bigbluebutton/bbb-conf/
cp conf-exit_sound.wav /etc/bigbluebutton/bbb-conf/
cp conf-goodbye.wav /etc/bigbluebutton/bbb-conf/
cp conf-has_joined.wav /etc/bigbluebutton/bbb-conf/
cp conf-has_left.wav /etc/bigbluebutton/bbb-conf/
cp conf-is-locked.wav /etc/bigbluebutton/bbb-conf/
cp conf-is-unlocked.wav /etc/bigbluebutton/bbb-conf/
cp conf-kicked.wav /etc/bigbluebutton/bbb-conf/
cp conf-listener_in_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-listeners_in_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-locked.wav /etc/bigbluebutton/bbb-conf/
cp conf-members_in_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-muted.wav /etc/bigbluebutton/bbb-conf/
cp conf-number_of_listeners.wav /etc/bigbluebutton/bbb-conf/
cp conf-one_other_member_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-one_other_person_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-other_persons_conference.wav /etc/bigbluebutton/bbb-conf/
cp conf-pin.wav /etc/bigbluebutton/bbb-conf/
cp conf-qna_mode.wav /etc/bigbluebutton/bbb-conf/
cp conf-unmuted.wav /etc/bigbluebutton/bbb-conf/
cp conf-welcome.wav /etc/bigbluebutton/bbb-conf/
cp conf-you_are_already_muted.wav /etc/bigbluebutton/bbb-conf/
cp conf-you_are_now_bidirectionally_muted.wav /etc/bigbluebutton/bbb-conf/
cp conf-alone.wav /etc/bigbluebutton/bbb-conf/
cp conf-bad-pin.wav /etc/bigbluebutton/bbb-conf/
cp conf-conference_is_full.wav /etc/bigbluebutton/bbb-conf/
cp conf-conference_is_in_qna_mode.wav /etc/bigbluebutton/bbb-conf/
cp conf-conference_will_start_shortly.wav /etc/bigbluebutton/bbb-conf/
cp conf-enter_conf_number.wav /etc/bigbluebutton/bbb-conf/

echo "Sesler ve özelleştirme dosyalarını sunucuda /etc/bigbluebutton/bbb-conf/ adresine aldık ki bundan sonraki tüm güncellemelerde kendiliğinden işlem yapsın şimdi ise bbb yeniden başlayacak"
bbb-conf --restart
